version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --port 4200 --poll 500 --disable-host-check
    restart: unless-stopped