version: '3.8'

services:
  janalya-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: janalya-web
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --port 4200 --poll 500 --disable-host-check
    networks:
      - janalya-network

networks:
  janalya-network:
    driver: bridge 